remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: OmniChat Documentation
description:  A powerful CLI tool that combines multiple AI models (OpenAI, Groq) for chat, image generation, and content creation. Features streaming responses, conversation history, and multi-format exports.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
