remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: OmniChat Documentation
description: Documentation for OmniChat - A Unified Chat Platform
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
